credentials:
  usernames:
    chubi:
      email: 'vic.penaj@gmail.com'
      first_name: 'Vicente'
      last_name: 'Pena'
      password: '$2b$12$IkZfvc4weLkbAREmmSeEoeShn4dwR8AfoRbS8hmtL3wYOo7QSwFCG'  # Este ser치 reemplazado por el hash autom치ticamente
      roles:
        - 'admin'
        - 'editor'
        - 'viewer'
    nacho:
      email: 'ignacioberriosvb@gmail.com'
      first_name: 'Ignacio'
      last_name: 'Berrios'
      password: '$2b$12$xX3lN5c8Oz06zR27fZzeVOPC7YHGrG2kWO48wFYqOyKuaXvSgnrde'  # Este ser치 reemplazado por el hash autom치ticamente
      roles:
        - 'viewer'

cookie:
  expiry_days: 30
  key: 'some_signature_key' # Debe ser una cadena segura
  name: 'some_cookie_name'

preauthorized:
  emails:
    - 'vic.penaj@gmail.com'
    - 'ignacioberriosvb@gmail.com'
